### ISSUE TITLE
Algolia index objectID is undefined

### ISSUE THREAD

**Issue by bcartier** [dimitrov-adrian/directus-extension-searchsync#13]
When running the CLI command to reindex, the first record in the Algolia index is being updated over and over again for every  Item in the Collection.  I think it's because the ObjectID is set as "undefined", so Algolia is finding an existing record with that ObjectID and updating it, rather than adding a new record. 

I was originally just configuring search-sync using a json file, passing just Item fields. In this case, I think Algolia was auto-generating the ObjectID. Since it was always "undefined", I tried using a js-based config file so I could pass the item.id as the Algolia ObjectID - no difference. 

SearchSync v1.0.2
Directus 9.2.1

**Comment by dimitrov-adrian** [comment]
What is the name of the Primary Key field?

**Comment by bcartier** [comment]
For Algolia, it always uses **objectID** as the primary key of its indexes. So, if you create a record in an Algolia index and don't specify an objectID, Algolia assigns one automatically. The searchsysnc extension was previously working this way, but I think a recent update may have changed something, and now objectID is being set as "undefined" for some reason. This changes how Algolia responds to the API call, and it keeps overwriting the same record (with a primary key of "undefined" for every Item in Directus)

**Comment by bcartier** [comment]
I'm trying to send the item.id from Directus as the objectID, but item.id doesn't seem to be accessible using transform callback. Also, passing any value using the "objectID" key, doesn't work (even a plain string).

 **Here's my config:**

const config = {
	server: {
		type: 'algolia',
		appId: '************',
		key: '************',
	},
	reindexOnStart: false,
	batchLimit: 100,
	collections: {
		naics_2017_examples_en: {
            indexName: "naics_2017_examples_en",
			filter: {
				status: 'published',
			},
    
			fields: ['example', 'exceptions', 'naics.id'],   // these appear in the algolia index
			transform: (item, { flattenObject, striptags }) => {
				return {
					...flattenObject(item),
					
					// ideally I want the objectId to be item.id, but I'm trying to set it to a known-working value here
					objectID: item.example, // doesn't work, shows as undefined in algolia index
					
					test1: item.example, //  works, shows in algolia index
					test2: item.id,  // doesn't work. The test2 key doesn't even appear in algolia index
					someCustomValue: 'Just a test string', // works, shows in algolia index
				};
			}

		}
	},
};

// Use as object.
module.exports = config;

**Here is the resulting algolia index:**

{
      "example": "vegetable (e.g., broccoli, Brussels sprout, cabbage, carrot, cauliflower), farming",
      "exceptions": "",
      "naics.id": "111219",
      "test1": "vegetable (e.g., broccoli, Brussels sprout, cabbage, carrot, cauliflower), farming",
      "someCustomValue": "Just a test string",
      "objectID": "undefined"
}

**Comment by bcartier** [comment]
I rolled back to how I had it configured when is was working for me (using a json config file). Basically, from what I now understand, the extension determines the primary key of the configured collection, and passes that value to Algolia as the objectID. This no longer happens. I wonder if something changed in the latest versions of Directus that changes how you determine the primary key for a collection. Maybe this line on create-indexer.js (line 69) no longer works?

 `const pk = schema.collections[collection].primary;`

**Comment by dimitrov-adrian** [comment]
Doesn't looks as there, at least with my tests it get correct primary key name, and pass correctly to the request. I also make different tests with algolia with different primary key names, and all seems to works for me, so cannot reproduce.

Anyway, I'll continue to dig on it.

**Comment by bcartier** [comment]
Thanks for looking into it. Maybe there's something wrong in my configuration? Here is my config where I have a collection named "naics_2017_examples_en", and it has text fields "example" and "exceptions". The "naics" field is a o2m relationship field (and populates the index with the foreign key):

```
{
	"server": {
		"type": "algolia",
	    "appId": "*********",
	    "key": "********************"
	},
	"batchLimit": 100,
	"reindexOnStart": false,
	"collections": {
	
		"naics_2017_examples_en": {
		
			"indexName": "naics_2017_examples_en_test",
	

			"filter": {
				"status": "published"
			},
			"fields": ["example",  "exceptions", "naics"]
		}
	}
}
```
.... and here is the Algolia index. This one index entry gets overwritten for every item in the collection when I run "npx directus extension:searchsync index" (the exceptions field is supposed to be blank in this example):

```
{
  "example": "fruit cocktail, canned, manufacturing",
  "exceptions": "",
  "naics": "311420",
  "objectID": "undefined"
}
```

**Comment by dimitrov-adrian** [comment]
I think it should be fixed now. The issue indeed was with the missing id field passing to algolia indexer when using filter fields.

Thanks for all the report!

**Comment by bcartier** [comment]
Thanks so much for your help!
