### ISSUE TITLE
How can i use this module?

### ISSUE THREAD

**Issue by ferdigokdemir** [dimitrov-adrian/directus-extension-searchsync#5]
Have an installation step?

**Comment by dimitrov-adrian** [comment]
Not yet.

Place the downloaded into your extensions directory as for example `extensions/hooks/directus-extension-searchsync` 
, create config file (searchsync.config.json) as in the example, then on the module directory run `npm install` and restart directus

I'll leave the issue opened till write proper installation guide.

**Comment by dimitrov-adrian** [comment]
Closing with 575fe91
