### ISSUE TITLE
Reindexing collection is limited to 100 items

### ISSUE THREAD

**Issue by benosman** [dimitrov-adrian/directus-extension-searchsync#9]
Hello again,

On my site, I have reindexOnStart enabled, but  i've noticed that the call to readByQuery only returns a maximum of 100 items. If you have more items than that in the collection, then some items will not be indexed.

The function either needs to remove the limit, or work in batches until complete.

**Comment by dimitrov-adrian** [comment]
Oh, yes, that because the internal limit.

I think batched will be best here.

Also I hope https://github.com/directus/directus/pull/7675 taking place soon or by some shape, so cli command for reindexing will be good addition too.

**Comment by dimitrov-adrian** [comment]
It should be fixed now, thanks!
